#
# Конфигурационный файл WorldGuard.
#
# Это файл конфигураций мира. Это влияет только на один
# соответствующий мир.
#
# О редактировании этого файла:
# - НЕ ИСПОЛЬЗОВАТЬ TAB. Вы должны использовать пробелы иначе Bukkit будет жаловаться. Если
#   вы используете редактор, такой как Notepad++ (рекомендуется для пользователей Windows), вы
#   должны настроить его на "заменить TAB на пробелы." В Notepad++, это можно
#   изменить в Опции > Настройки > Настройки табуляци.
# - Не избавиляйтесь от отступов. Они смещены, поэтому некоторые записи
#   в категориях (как "enforce-single-session" находится в категории "protection")
# - Если вы хотите проверить формат этого файла, прежде чем положить его
#   в WorldGuard, вставьте его в http://yaml-online-parser.appspot.com/
#   и посмотрите полученные "ОШИБКА:".
# - Строки, начинающие с # называются комментариями, поэтому они игнорируются.
#

# -- Это должно быть автоматически заменено плагином в игре --